baseURL = 'https://unixwmbr.github.io/'
languageCode = 'pt-br'
title = 'unixwmbr'
theme = "terminal"

[params]
        themeColor = "green"
        centerTheme = true
        Toc = true
        TocTitle = "Tabela de Conteúdo"
        showLastUpdated = true

